plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.6
  Exclude:
    - 'db/schema.rb'
    - 'db/*_schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false